// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import "github.com/jackc/pgx/v5/pgtype"

type TransactionStatus string

const (
	TransactionStatusPending    TransactionStatus = "pending"
	TransactionStatusProcessing TransactionStatus = "processing"
	TransactionStatusCompleted  TransactionStatus = "completed"
	TransactionStatusFailed     TransactionStatus = "failed"
	TransactionStatusReversed   TransactionStatus = "reversed"
)

type Transaction struct {
	ID             pgtype.UUID        `json:"id"`
	IdempotencyKey string             `json:"idempotency_key"`
	FromAccountID  pgtype.UUID        `json:"from_account_id"`
	ToAccountID    pgtype.UUID        `json:"to_account_id"`
	Amount         int64              `json:"amount"`
	Currency       string             `json:"currency"`
	Description    string             `json:"description"`
	Status         TransactionStatus  `json:"status"`
	FailureReason  string             `json:"failure_reason"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}
