// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CountTransactionsByAccount(ctx context.Context, accountID pgtype.UUID) (int64, error)
	CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error)
	GetTransactionByID(ctx context.Context, id pgtype.UUID) (Transaction, error)
	GetTransactionByIdempotencyKey(ctx context.Context, idempotencyKey string) (Transaction, error)
	GetTransactionsByAccount(ctx context.Context, arg GetTransactionsByAccountParams) ([]Transaction, error)
	UpdateTransactionStatus(ctx context.Context, arg UpdateTransactionStatusParams) (Transaction, error)
	UpdateTransactionStatusWithReason(ctx context.Context, arg UpdateTransactionStatusWithReasonParams) (Transaction, error)
}

var _ Querier = (*Queries)(nil)
