// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: transaction.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countTransactionsByAccount = `-- name: CountTransactionsByAccount :one
SELECT COUNT(*)
FROM transactions
WHERE from_account_id = $1 OR to_account_id = $1
`

func (q *Queries) CountTransactionsByAccount(ctx context.Context, accountID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countTransactionsByAccount, accountID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createTransaction = `-- name: CreateTransaction :one
INSERT INTO transactions (
    idempotency_key,
    from_account_id,
    to_account_id,
    amount,
    currency,
    description,
    status
) VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, idempotency_key, from_account_id, to_account_id, amount, currency, description, status, failure_reason, created_at, updated_at
`

type CreateTransactionParams struct {
	IdempotencyKey string            `json:"idempotency_key"`
	FromAccountID  pgtype.UUID       `json:"from_account_id"`
	ToAccountID    pgtype.UUID       `json:"to_account_id"`
	Amount         int64             `json:"amount"`
	Currency       string            `json:"currency"`
	Description    string            `json:"description"`
	Status         TransactionStatus `json:"status"`
}

func (q *Queries) CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, createTransaction,
		arg.IdempotencyKey,
		arg.FromAccountID,
		arg.ToAccountID,
		arg.Amount,
		arg.Currency,
		arg.Description,
		arg.Status,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.IdempotencyKey,
		&i.FromAccountID,
		&i.ToAccountID,
		&i.Amount,
		&i.Currency,
		&i.Description,
		&i.Status,
		&i.FailureReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTransactionByID = `-- name: GetTransactionByID :one
SELECT id, idempotency_key, from_account_id, to_account_id, amount, currency, description, status, failure_reason, created_at, updated_at
FROM transactions
WHERE id = $1
`

func (q *Queries) GetTransactionByID(ctx context.Context, id pgtype.UUID) (Transaction, error) {
	row := q.db.QueryRow(ctx, getTransactionByID, id)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.IdempotencyKey,
		&i.FromAccountID,
		&i.ToAccountID,
		&i.Amount,
		&i.Currency,
		&i.Description,
		&i.Status,
		&i.FailureReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTransactionByIdempotencyKey = `-- name: GetTransactionByIdempotencyKey :one
SELECT id, idempotency_key, from_account_id, to_account_id, amount, currency, description, status, failure_reason, created_at, updated_at
FROM transactions
WHERE idempotency_key = $1
`

func (q *Queries) GetTransactionByIdempotencyKey(ctx context.Context, idempotencyKey string) (Transaction, error) {
	row := q.db.QueryRow(ctx, getTransactionByIdempotencyKey, idempotencyKey)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.IdempotencyKey,
		&i.FromAccountID,
		&i.ToAccountID,
		&i.Amount,
		&i.Currency,
		&i.Description,
		&i.Status,
		&i.FailureReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTransactionsByAccount = `-- name: GetTransactionsByAccount :many
SELECT id, idempotency_key, from_account_id, to_account_id, amount, currency, description, status, failure_reason, created_at, updated_at
FROM transactions
WHERE from_account_id = $1 OR to_account_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type GetTransactionsByAccountParams struct {
	FromAccountID pgtype.UUID `json:"from_account_id"`
	Limit         int32       `json:"limit"`
	Offset        int32       `json:"offset"`
}

func (q *Queries) GetTransactionsByAccount(ctx context.Context, arg GetTransactionsByAccountParams) ([]Transaction, error) {
	rows, err := q.db.Query(ctx, getTransactionsByAccount, arg.FromAccountID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Transaction{}
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.IdempotencyKey,
			&i.FromAccountID,
			&i.ToAccountID,
			&i.Amount,
			&i.Currency,
			&i.Description,
			&i.Status,
			&i.FailureReason,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTransactionStatus = `-- name: UpdateTransactionStatus :one
UPDATE transactions
SET status = $2, updated_at = NOW()
WHERE id = $1
RETURNING id, idempotency_key, from_account_id, to_account_id, amount, currency, description, status, failure_reason, created_at, updated_at
`

type UpdateTransactionStatusParams struct {
	ID     pgtype.UUID       `json:"id"`
	Status TransactionStatus `json:"status"`
}

func (q *Queries) UpdateTransactionStatus(ctx context.Context, arg UpdateTransactionStatusParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, updateTransactionStatus, arg.ID, arg.Status)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.IdempotencyKey,
		&i.FromAccountID,
		&i.ToAccountID,
		&i.Amount,
		&i.Currency,
		&i.Description,
		&i.Status,
		&i.FailureReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateTransactionStatusWithReason = `-- name: UpdateTransactionStatusWithReason :one
UPDATE transactions
SET status = $2, failure_reason = $3, updated_at = NOW()
WHERE id = $1
RETURNING id, idempotency_key, from_account_id, to_account_id, amount, currency, description, status, failure_reason, created_at, updated_at
`

type UpdateTransactionStatusWithReasonParams struct {
	ID            pgtype.UUID       `json:"id"`
	Status        TransactionStatus `json:"status"`
	FailureReason string            `json:"failure_reason"`
}

func (q *Queries) UpdateTransactionStatusWithReason(ctx context.Context, arg UpdateTransactionStatusWithReasonParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, updateTransactionStatusWithReason, arg.ID, arg.Status, arg.FailureReason)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.IdempotencyKey,
		&i.FromAccountID,
		&i.ToAccountID,
		&i.Amount,
		&i.Currency,
		&i.Description,
		&i.Status,
		&i.FailureReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
