// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type KycStatus string

const (
	KycStatusNone     KycStatus = "none"
	KycStatusPending  KycStatus = "pending"
	KycStatusVerified KycStatus = "verified"
	KycStatusRejected KycStatus = "rejected"
)

func (e *KycStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = KycStatus(s)
	case string:
		*e = KycStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for KycStatus: %T", src)
	}
	return nil
}

type NullKycStatus struct {
	KycStatus KycStatus `json:"kyc_status"`
	Valid     bool      `json:"valid"` // Valid is true if KycStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullKycStatus) Scan(value interface{}) error {
	if value == nil {
		ns.KycStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.KycStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullKycStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.KycStatus), nil
}

type UserStatus string

const (
	UserStatusPending UserStatus = "pending"
	UserStatusActive  UserStatus = "active"
	UserStatusBlocked UserStatus = "blocked"
	UserStatusDeleted UserStatus = "deleted"
)

func (e *UserStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserStatus(s)
	case string:
		*e = UserStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for UserStatus: %T", src)
	}
	return nil
}

type NullUserStatus struct {
	UserStatus UserStatus `json:"user_status"`
	Valid      bool       `json:"valid"` // Valid is true if UserStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserStatus) Scan(value interface{}) error {
	if value == nil {
		ns.UserStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserStatus), nil
}

type RefreshToken struct {
	ID          pgtype.UUID        `json:"id"`
	UserID      pgtype.UUID        `json:"user_id"`
	DeviceInfo  pgtype.Text        `json:"device_info"`
	RotatedFrom pgtype.UUID        `json:"rotated_from"`
	Revoked     pgtype.Bool        `json:"revoked"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
	LastUsedAt  pgtype.Timestamptz `json:"last_used_at"`
}

type User struct {
	ID           pgtype.UUID        `json:"id"`
	Email        string             `json:"email"`
	Phone        string             `json:"phone"`
	PasswordHash string             `json:"password_hash"`
	FirstName    string             `json:"first_name"`
	LastName     string             `json:"last_name"`
	Status       UserStatus         `json:"status"`
	KycStatus    KycStatus          `json:"kyc_status"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}
