// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: refresh_token.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const cleanExpiredTokens = `-- name: CleanExpiredTokens :exec
delete from refresh_tokens
where expires_at < now()
`

func (q *Queries) CleanExpiredTokens(ctx context.Context) error {
	_, err := q.db.Exec(ctx, cleanExpiredTokens)
	return err
}

const consumeRefreshToken = `-- name: ConsumeRefreshToken :one
UPDATE refresh_tokens 
SET last_used_at = NOW()
WHERE id = $1 
  AND last_used_at IS NULL
  AND revoked = false 
  AND expires_at > NOW()
RETURNING id, user_id, device_info, rotated_from, revoked, created_at, expires_at, last_used_at
`

func (q *Queries) ConsumeRefreshToken(ctx context.Context, id pgtype.UUID) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, consumeRefreshToken, id)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DeviceInfo,
		&i.RotatedFrom,
		&i.Revoked,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.LastUsedAt,
	)
	return i, err
}

const createRefreshToken = `-- name: CreateRefreshToken :one
insert into refresh_tokens (user_id, device_info, expires_at, rotated_from)
values ($1, $2, $3, $4)
returning id, user_id, device_info, rotated_from, revoked, created_at, expires_at, last_used_at
`

type CreateRefreshTokenParams struct {
	UserID      pgtype.UUID        `json:"user_id"`
	DeviceInfo  pgtype.Text        `json:"device_info"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
	RotatedFrom pgtype.UUID        `json:"rotated_from"`
}

func (q *Queries) CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, createRefreshToken,
		arg.UserID,
		arg.DeviceInfo,
		arg.ExpiresAt,
		arg.RotatedFrom,
	)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DeviceInfo,
		&i.RotatedFrom,
		&i.Revoked,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.LastUsedAt,
	)
	return i, err
}

const getRefreshToken = `-- name: GetRefreshToken :one
select id, user_id, device_info, rotated_from, revoked, created_at, expires_at, last_used_at
from refresh_tokens
where id = $1
  and revoked = false
  and expires_at > now()
`

func (q *Queries) GetRefreshToken(ctx context.Context, id pgtype.UUID) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, getRefreshToken, id)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DeviceInfo,
		&i.RotatedFrom,
		&i.Revoked,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.LastUsedAt,
	)
	return i, err
}

const getRefreshTokenForUpdate = `-- name: GetRefreshTokenForUpdate :one
SELECT id, user_id, device_info, rotated_from, revoked, created_at, expires_at, last_used_at FROM refresh_tokens
WHERE id = $1 AND revoked = false AND expires_at > NOW()
FOR UPDATE
`

func (q *Queries) GetRefreshTokenForUpdate(ctx context.Context, id pgtype.UUID) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, getRefreshTokenForUpdate, id)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DeviceInfo,
		&i.RotatedFrom,
		&i.Revoked,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.LastUsedAt,
	)
	return i, err
}

const getUserActiveTokens = `-- name: GetUserActiveTokens :many
select id, user_id, device_info, rotated_from, revoked, created_at, expires_at, last_used_at
from refresh_tokens
where user_id = $1
  and revoked = false
  and expires_at > now()
order by created_at desc
`

func (q *Queries) GetUserActiveTokens(ctx context.Context, userID pgtype.UUID) ([]RefreshToken, error) {
	rows, err := q.db.Query(ctx, getUserActiveTokens, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RefreshToken{}
	for rows.Next() {
		var i RefreshToken
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.DeviceInfo,
			&i.RotatedFrom,
			&i.Revoked,
			&i.CreatedAt,
			&i.ExpiresAt,
			&i.LastUsedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeAllUserTokens = `-- name: RevokeAllUserTokens :exec
update refresh_tokens
set revoked = true
where user_id = $1
  and revoked = false
`

func (q *Queries) RevokeAllUserTokens(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, revokeAllUserTokens, userID)
	return err
}

const revokeRefreshToken = `-- name: RevokeRefreshToken :exec
update refresh_tokens
set revoked = true
where id = $1
`

func (q *Queries) RevokeRefreshToken(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, revokeRefreshToken, id)
	return err
}

const revokeTokenFamily = `-- name: RevokeTokenFamily :exec
with recursive token_family as (
  select id
  from refresh_tokens
  where refresh_tokens.id = $1
  union
  select rt.id
  from refresh_tokens rt
    join token_family tf on rt.rotated_from = tf.id
)
update refresh_tokens
set revoked = true
where refresh_tokens.id in (
    select token_family.id
    from token_family
  )
`

func (q *Queries) RevokeTokenFamily(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, revokeTokenFamily, id)
	return err
}

const updateRefreshTokenLastUsed = `-- name: UpdateRefreshTokenLastUsed :exec
update refresh_tokens
set last_used_at = now()
where id = $1
`

func (q *Queries) UpdateRefreshTokenLastUsed(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, updateRefreshTokenLastUsed, id)
	return err
}
