services:
  user-db:
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: user_service
      POSTGRES_PASSWORD: user_service_pass
      POSTGRES_DB: user_db
    ports:
      - "5433:5432"
    volumes:
      - user-db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user_service -d user_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  user-redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  user-audit-db:
    image: mongo:8
    ports:
      - "27017:27017"
    volumes:
      - user-audit-db-data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      timeout: 5s
      retries: 5

  user:
    build:
      context: ../../
      dockerfile: services/user/Dockerfile
    ports:
      - "50051:50051"
    environment:
      GRPC_PORT: "50051"
      DB_HOST: user-db
      DB_PORT: "5432"
      DB_USER: user_service
      DB_PASSWORD: user_service_pass
      DB_NAME: user_db
      DB_SSL_MODE: disable
      KAFKA_BROKERS: ""
      MONGO_URI: "mongodb://user-audit-db:27017"
      MONGO_AUDIT_DB: audit
      REDIS_HOST: user-redis
      REDIS_PORT: "6379"
      PRIVATE_KEY_PATH: /keys/private.pem
    volumes:
      - ../../keys:/keys:ro
    depends_on:
      user-db:
        condition: service_healthy
      user-audit-db:
        condition: service_healthy
      user-redis:
        condition: service_healthy

volumes:
  user-db-data:
  user-audit-db-data:
