// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: account.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAccount = `-- name: CreateAccount :one
INSERT INTO accounts (
        user_id,
        currency,
        balance,
        hold_amount,
        status,
        created_at,
        updated_at
    )
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, user_id, currency, balance, hold_amount, status, created_at, updated_at
`

type CreateAccountParams struct {
	UserID     pgtype.UUID        `json:"user_id"`
	Currency   string             `json:"currency"`
	Balance    int64              `json:"balance"`
	HoldAmount int64              `json:"hold_amount"`
	Status     AccountStatus      `json:"status"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error) {
	row := q.db.QueryRow(ctx, createAccount,
		arg.UserID,
		arg.Currency,
		arg.Balance,
		arg.HoldAmount,
		arg.Status,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Currency,
		&i.Balance,
		&i.HoldAmount,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const existsAccountByUserAndCurrency = `-- name: ExistsAccountByUserAndCurrency :one
SELECT EXISTS(
        SELECT 1
        FROM accounts
        WHERE user_id = $1
            AND currency = $2
    )
`

type ExistsAccountByUserAndCurrencyParams struct {
	UserID   pgtype.UUID `json:"user_id"`
	Currency string      `json:"currency"`
}

func (q *Queries) ExistsAccountByUserAndCurrency(ctx context.Context, arg ExistsAccountByUserAndCurrencyParams) (bool, error) {
	row := q.db.QueryRow(ctx, existsAccountByUserAndCurrency, arg.UserID, arg.Currency)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const getAccountByID = `-- name: GetAccountByID :one
SELECT id, user_id, currency, balance, hold_amount, status, created_at, updated_at
FROM accounts
WHERE id = $1
`

func (q *Queries) GetAccountByID(ctx context.Context, id pgtype.UUID) (Account, error) {
	row := q.db.QueryRow(ctx, getAccountByID, id)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Currency,
		&i.Balance,
		&i.HoldAmount,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAccountByIDForUpdate = `-- name: GetAccountByIDForUpdate :one
SELECT id, user_id, currency, balance, hold_amount, status, created_at, updated_at
FROM accounts
WHERE id = $1 FOR
UPDATE
`

func (q *Queries) GetAccountByIDForUpdate(ctx context.Context, id pgtype.UUID) (Account, error) {
	row := q.db.QueryRow(ctx, getAccountByIDForUpdate, id)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Currency,
		&i.Balance,
		&i.HoldAmount,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAccountByUserAndCurrency = `-- name: GetAccountByUserAndCurrency :one
SELECT id, user_id, currency, balance, hold_amount, status, created_at, updated_at
FROM accounts
WHERE user_id = $1
    AND currency = $2
`

type GetAccountByUserAndCurrencyParams struct {
	UserID   pgtype.UUID `json:"user_id"`
	Currency string      `json:"currency"`
}

func (q *Queries) GetAccountByUserAndCurrency(ctx context.Context, arg GetAccountByUserAndCurrencyParams) (Account, error) {
	row := q.db.QueryRow(ctx, getAccountByUserAndCurrency, arg.UserID, arg.Currency)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Currency,
		&i.Balance,
		&i.HoldAmount,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAccountsByUserID = `-- name: GetAccountsByUserID :many
SELECT id, user_id, currency, balance, hold_amount, status, created_at, updated_at
FROM accounts
WHERE user_id = $1
ORDER BY created_at
`

func (q *Queries) GetAccountsByUserID(ctx context.Context, userID pgtype.UUID) ([]Account, error) {
	rows, err := q.db.Query(ctx, getAccountsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Account{}
	for rows.Next() {
		var i Account
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Currency,
			&i.Balance,
			&i.HoldAmount,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAccount = `-- name: UpdateAccount :one
UPDATE accounts
SET balance = $2,
    hold_amount = $3,
    status = $4,
    updated_at = $5
WHERE id = $1
RETURNING id, user_id, currency, balance, hold_amount, status, created_at, updated_at
`

type UpdateAccountParams struct {
	ID         pgtype.UUID        `json:"id"`
	Balance    int64              `json:"balance"`
	HoldAmount int64              `json:"hold_amount"`
	Status     AccountStatus      `json:"status"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpdateAccount(ctx context.Context, arg UpdateAccountParams) (Account, error) {
	row := q.db.QueryRow(ctx, updateAccount,
		arg.ID,
		arg.Balance,
		arg.HoldAmount,
		arg.Status,
		arg.UpdatedAt,
	)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Currency,
		&i.Balance,
		&i.HoldAmount,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
