// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: hold.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createHold = `-- name: CreateHold :one
INSERT INTO holds (
        account_id,
        transaction_id,
        amount,
        description,
        status,
        created_at
    )
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, account_id, transaction_id, amount, description, status, created_at, released_at
`

type CreateHoldParams struct {
	AccountID     pgtype.UUID        `json:"account_id"`
	TransactionID pgtype.UUID        `json:"transaction_id"`
	Amount        int64              `json:"amount"`
	Description   pgtype.Text        `json:"description"`
	Status        HoldStatus         `json:"status"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateHold(ctx context.Context, arg CreateHoldParams) (Hold, error) {
	row := q.db.QueryRow(ctx, createHold,
		arg.AccountID,
		arg.TransactionID,
		arg.Amount,
		arg.Description,
		arg.Status,
		arg.CreatedAt,
	)
	var i Hold
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.TransactionID,
		&i.Amount,
		&i.Description,
		&i.Status,
		&i.CreatedAt,
		&i.ReleasedAt,
	)
	return i, err
}

const getActiveHoldsByAccountID = `-- name: GetActiveHoldsByAccountID :many
SELECT id, account_id, transaction_id, amount, description, status, created_at, released_at
FROM holds
WHERE account_id = $1
    AND status = 'active'
ORDER BY created_at
`

func (q *Queries) GetActiveHoldsByAccountID(ctx context.Context, accountID pgtype.UUID) ([]Hold, error) {
	rows, err := q.db.Query(ctx, getActiveHoldsByAccountID, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Hold{}
	for rows.Next() {
		var i Hold
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.TransactionID,
			&i.Amount,
			&i.Description,
			&i.Status,
			&i.CreatedAt,
			&i.ReleasedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getHoldByID = `-- name: GetHoldByID :one
SELECT id, account_id, transaction_id, amount, description, status, created_at, released_at
FROM holds
WHERE id = $1
`

func (q *Queries) GetHoldByID(ctx context.Context, id pgtype.UUID) (Hold, error) {
	row := q.db.QueryRow(ctx, getHoldByID, id)
	var i Hold
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.TransactionID,
		&i.Amount,
		&i.Description,
		&i.Status,
		&i.CreatedAt,
		&i.ReleasedAt,
	)
	return i, err
}

const getHoldByTransactionID = `-- name: GetHoldByTransactionID :one
SELECT id, account_id, transaction_id, amount, description, status, created_at, released_at
FROM holds
WHERE account_id = $1
    AND transaction_id = $2
`

type GetHoldByTransactionIDParams struct {
	AccountID     pgtype.UUID `json:"account_id"`
	TransactionID pgtype.UUID `json:"transaction_id"`
}

func (q *Queries) GetHoldByTransactionID(ctx context.Context, arg GetHoldByTransactionIDParams) (Hold, error) {
	row := q.db.QueryRow(ctx, getHoldByTransactionID, arg.AccountID, arg.TransactionID)
	var i Hold
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.TransactionID,
		&i.Amount,
		&i.Description,
		&i.Status,
		&i.CreatedAt,
		&i.ReleasedAt,
	)
	return i, err
}

const getHoldByTransactionIDForUpdate = `-- name: GetHoldByTransactionIDForUpdate :one
SELECT id, account_id, transaction_id, amount, description, status, created_at, released_at
FROM holds
WHERE account_id = $1
    AND transaction_id = $2 FOR
UPDATE
`

type GetHoldByTransactionIDForUpdateParams struct {
	AccountID     pgtype.UUID `json:"account_id"`
	TransactionID pgtype.UUID `json:"transaction_id"`
}

func (q *Queries) GetHoldByTransactionIDForUpdate(ctx context.Context, arg GetHoldByTransactionIDForUpdateParams) (Hold, error) {
	row := q.db.QueryRow(ctx, getHoldByTransactionIDForUpdate, arg.AccountID, arg.TransactionID)
	var i Hold
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.TransactionID,
		&i.Amount,
		&i.Description,
		&i.Status,
		&i.CreatedAt,
		&i.ReleasedAt,
	)
	return i, err
}

const updateHold = `-- name: UpdateHold :one
UPDATE holds
SET status = $2,
    released_at = $3
WHERE id = $1
RETURNING id, account_id, transaction_id, amount, description, status, created_at, released_at
`

type UpdateHoldParams struct {
	ID         pgtype.UUID        `json:"id"`
	Status     HoldStatus         `json:"status"`
	ReleasedAt pgtype.Timestamptz `json:"released_at"`
}

func (q *Queries) UpdateHold(ctx context.Context, arg UpdateHoldParams) (Hold, error) {
	row := q.db.QueryRow(ctx, updateHold, arg.ID, arg.Status, arg.ReleasedAt)
	var i Hold
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.TransactionID,
		&i.Amount,
		&i.Description,
		&i.Status,
		&i.CreatedAt,
		&i.ReleasedAt,
	)
	return i, err
}
