// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type AccountStatus string

const (
	AccountStatusActive  AccountStatus = "active"
	AccountStatusBlocked AccountStatus = "blocked"
	AccountStatusClosed  AccountStatus = "closed"
)

func (e *AccountStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AccountStatus(s)
	case string:
		*e = AccountStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for AccountStatus: %T", src)
	}
	return nil
}

type NullAccountStatus struct {
	AccountStatus AccountStatus `json:"account_status"`
	Valid         bool          `json:"valid"` // Valid is true if AccountStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAccountStatus) Scan(value interface{}) error {
	if value == nil {
		ns.AccountStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AccountStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAccountStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AccountStatus), nil
}

type HoldStatus string

const (
	HoldStatusActive   HoldStatus = "active"
	HoldStatusReleased HoldStatus = "released"
	HoldStatusExecuted HoldStatus = "executed"
)

func (e *HoldStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = HoldStatus(s)
	case string:
		*e = HoldStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for HoldStatus: %T", src)
	}
	return nil
}

type NullHoldStatus struct {
	HoldStatus HoldStatus `json:"hold_status"`
	Valid      bool       `json:"valid"` // Valid is true if HoldStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullHoldStatus) Scan(value interface{}) error {
	if value == nil {
		ns.HoldStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.HoldStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullHoldStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.HoldStatus), nil
}

type OperationType string

const (
	OperationTypeCredit      OperationType = "credit"
	OperationTypeDebit       OperationType = "debit"
	OperationTypeHold        OperationType = "hold"
	OperationTypeHoldRelease OperationType = "hold_release"
)

func (e *OperationType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = OperationType(s)
	case string:
		*e = OperationType(s)
	default:
		return fmt.Errorf("unsupported scan type for OperationType: %T", src)
	}
	return nil
}

type NullOperationType struct {
	OperationType OperationType `json:"operation_type"`
	Valid         bool          `json:"valid"` // Valid is true if OperationType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullOperationType) Scan(value interface{}) error {
	if value == nil {
		ns.OperationType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.OperationType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullOperationType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.OperationType), nil
}

type Account struct {
	ID         pgtype.UUID        `json:"id"`
	UserID     pgtype.UUID        `json:"user_id"`
	Currency   string             `json:"currency"`
	Balance    int64              `json:"balance"`
	HoldAmount int64              `json:"hold_amount"`
	Status     AccountStatus      `json:"status"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

type Hold struct {
	ID            pgtype.UUID        `json:"id"`
	AccountID     pgtype.UUID        `json:"account_id"`
	TransactionID pgtype.UUID        `json:"transaction_id"`
	Amount        int64              `json:"amount"`
	Description   pgtype.Text        `json:"description"`
	Status        HoldStatus         `json:"status"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	ReleasedAt    pgtype.Timestamptz `json:"released_at"`
}

type Operation struct {
	ID            pgtype.UUID        `json:"id"`
	AccountID     pgtype.UUID        `json:"account_id"`
	Type          OperationType      `json:"type"`
	Amount        int64              `json:"amount"`
	BalanceAfter  int64              `json:"balance_after"`
	TransactionID pgtype.UUID        `json:"transaction_id"`
	Description   pgtype.Text        `json:"description"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}
