// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: operation.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countOperationsByAccountID = `-- name: CountOperationsByAccountID :one
SELECT COUNT(*)
FROM operations
WHERE account_id = $1
`

func (q *Queries) CountOperationsByAccountID(ctx context.Context, accountID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countOperationsByAccountID, accountID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createOperation = `-- name: CreateOperation :one
INSERT INTO operations (
        id,
        account_id,
        type,
        amount,
        balance_after,
        transaction_id,
        description,
        created_at
    )
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, account_id, type, amount, balance_after, transaction_id, description, created_at
`

type CreateOperationParams struct {
	ID            pgtype.UUID        `json:"id"`
	AccountID     pgtype.UUID        `json:"account_id"`
	Type          OperationType      `json:"type"`
	Amount        int64              `json:"amount"`
	BalanceAfter  int64              `json:"balance_after"`
	TransactionID pgtype.UUID        `json:"transaction_id"`
	Description   pgtype.Text        `json:"description"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateOperation(ctx context.Context, arg CreateOperationParams) (Operation, error) {
	row := q.db.QueryRow(ctx, createOperation,
		arg.ID,
		arg.AccountID,
		arg.Type,
		arg.Amount,
		arg.BalanceAfter,
		arg.TransactionID,
		arg.Description,
		arg.CreatedAt,
	)
	var i Operation
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Type,
		&i.Amount,
		&i.BalanceAfter,
		&i.TransactionID,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const getOperationByTransactionIDAndType = `-- name: GetOperationByTransactionIDAndType :one
SELECT id, account_id, type, amount, balance_after, transaction_id, description, created_at
FROM operations
WHERE account_id = $1
    AND transaction_id = $2
    AND type = $3
`

type GetOperationByTransactionIDAndTypeParams struct {
	AccountID     pgtype.UUID   `json:"account_id"`
	TransactionID pgtype.UUID   `json:"transaction_id"`
	Type          OperationType `json:"type"`
}

func (q *Queries) GetOperationByTransactionIDAndType(ctx context.Context, arg GetOperationByTransactionIDAndTypeParams) (Operation, error) {
	row := q.db.QueryRow(ctx, getOperationByTransactionIDAndType, arg.AccountID, arg.TransactionID, arg.Type)
	var i Operation
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Type,
		&i.Amount,
		&i.BalanceAfter,
		&i.TransactionID,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const getOperationsByAccountID = `-- name: GetOperationsByAccountID :many
SELECT id, account_id, type, amount, balance_after, transaction_id, description, created_at
FROM operations
WHERE account_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type GetOperationsByAccountIDParams struct {
	AccountID pgtype.UUID `json:"account_id"`
	Limit     int32       `json:"limit"`
	Offset    int32       `json:"offset"`
}

func (q *Queries) GetOperationsByAccountID(ctx context.Context, arg GetOperationsByAccountIDParams) ([]Operation, error) {
	rows, err := q.db.Query(ctx, getOperationsByAccountID, arg.AccountID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Operation{}
	for rows.Next() {
		var i Operation
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.Type,
			&i.Amount,
			&i.BalanceAfter,
			&i.TransactionID,
			&i.Description,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
