// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CountOperationsByAccountID(ctx context.Context, accountID pgtype.UUID) (int64, error)
	CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error)
	CreateHold(ctx context.Context, arg CreateHoldParams) (Hold, error)
	CreateOperation(ctx context.Context, arg CreateOperationParams) (Operation, error)
	ExistsAccountByUserAndCurrency(ctx context.Context, arg ExistsAccountByUserAndCurrencyParams) (bool, error)
	GetAccountByID(ctx context.Context, id pgtype.UUID) (Account, error)
	GetAccountByIDForUpdate(ctx context.Context, id pgtype.UUID) (Account, error)
	GetAccountByUserAndCurrency(ctx context.Context, arg GetAccountByUserAndCurrencyParams) (Account, error)
	GetAccountsByUserID(ctx context.Context, userID pgtype.UUID) ([]Account, error)
	GetActiveHoldsByAccountID(ctx context.Context, accountID pgtype.UUID) ([]Hold, error)
	GetHoldByID(ctx context.Context, id pgtype.UUID) (Hold, error)
	GetHoldByTransactionID(ctx context.Context, arg GetHoldByTransactionIDParams) (Hold, error)
	GetHoldByTransactionIDForUpdate(ctx context.Context, arg GetHoldByTransactionIDForUpdateParams) (Hold, error)
	GetOperationByTransactionIDAndType(ctx context.Context, arg GetOperationByTransactionIDAndTypeParams) (Operation, error)
	GetOperationsByAccountID(ctx context.Context, arg GetOperationsByAccountIDParams) ([]Operation, error)
	UpdateAccount(ctx context.Context, arg UpdateAccountParams) (Account, error)
	UpdateHold(ctx context.Context, arg UpdateHoldParams) (Hold, error)
}

var _ Querier = (*Queries)(nil)
